version: '3.8'

services:
  backend:
    container_name: ledmatrix-backend
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - minio
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: ledmatrix-storage
    restart: always
    env_file:
      - .env
    ports:
      - "9003:9001"
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: ledmatrix-proxy
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - minio
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  minio-data: