export enum WebsocketEventType {
    GET_SETTINGS = "GET_SETTINGS",
    GET_STATE = "GET_STATE",
    GET_SPOTIFY_UPDATE = "GET_SPOTIFY_UPDATES",
    GET_SINGLE_WEATHER_UPDATE = "GET_SINGLE_WEATHER_UPDATE",
    GET_WEATHER_UPDATES = "GET_WEATHER_UPDATES",
    STOP_SPOTIFY_UPDATES = "STOP_SPOTIFY_UPDATES",
    STOP_WEATHER_UPDATES = "STOP_WEATHER_UPDATES",
    ERROR = "ERROR",
    UPDATE_USER_SINGLE = "UPDATE_USER_SINGLE",
}
