export enum WebsocketEventType {
    GET_SETTINGS = "GET_SETTINGS",
    GET_STATE = "GET_STATE",
    SUBSCRIBE = "SUBSCRIBE",
    UNSUBSCRIBE = "UNSUBSCRIBE",
    ERROR = "ERROR",
    UPDATE_USER_SINGLE = "UPDATE_USER_SINGLE",
    SINGLE_WEATHER_UPDATE = "SINGLE_WEATHER_UPDATE",
    SINGLE_MUSIC_UPDATE = "SINGLE_MUSIC_UPDATE",
    SINGLE_TAMAGOTCHI_UPDATE = "SINGLE_TAMAGOTCHI_UPDATE",
}
